using System;

namespace NtFreX.Audio.Wasapi.Interop
{
    /// <summary>
    /// ksmedia.h
    /// </summary>
    [Flags]
    internal enum Speaker: uint
    {
        FRONT_LEFT = 0x1,
        FRONT_RIGHT	= 0x2,
        FRONT_CENTER = 0x4,
        LOW_FREQUENCY = 0x8,
        BACK_LEFT = 0x10,
        BACK_RIGHT = 0x20,
        FRONT_LEFT_OF_CENTER = 0x40,
        FRONT_RIGHT_OF_CENTER = 0x80,
        BACK_CENTER = 0x100,
        SIDE_LEFT = 0x200,
        SIDE_RIGHT = 0x400,
        TOP_CENTER = 0x800,
        TOP_FRONT_LEFT = 0x1000,
        TOP_FRONT_CENTER = 0x2000,
        TOP_FRONT_RIGHT = 0x4000,
        TOP_BACK_LEFT = 0x8000,
        TOP_BACK_CENTER = 0x10000,
        TOP_BACK_RIGHT = 0x20000,

        /// <summary>
        /// Used to specify that any possible permutation of speaker configurations
        /// </summary>
        SPEAKER_ALL = 0x80000000,

        KSAUDIO_MONO = FRONT_CENTER,
        KSAUDIO_1POINT1 = FRONT_CENTER | LOW_FREQUENCY,
        KSAUDIO_STEREO = FRONT_LEFT | FRONT_RIGHT,
        KSAUDIO_2POINT1 = FRONT_LEFT | FRONT_RIGHT | LOW_FREQUENCY,
        KSAUDIO_3POINT0 = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER,
        KSAUDIO_3POINT1 = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | LOW_FREQUENCY,
        KSAUDIO_QUAD = FRONT_LEFT | FRONT_RIGHT | BACK_LEFT | BACK_RIGHT,
        KSAUDIO_SURROUND = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | BACK_CENTER,
        KSAUDIO_5POINT0 = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | SIDE_LEFT | SIDE_RIGHT,
        KSAUDIO_5POINT1 = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | LOW_FREQUENCY | BACK_LEFT | BACK_RIGHT,
        KSAUDIO_7POINT0 = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | BACK_LEFT | BACK_RIGHT | SIDE_LEFT | SIDE_RIGHT,
        KSAUDIO_7POINT1 = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | LOW_FREQUENCY | BACK_LEFT | BACK_RIGHT | FRONT_LEFT_OF_CENTER | FRONT_RIGHT_OF_CENTER,

        KSAUDIO_5POINT1_SURROUND = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | LOW_FREQUENCY | SIDE_LEFT | SIDE_RIGHT,
        KSAUDIO_7POINT1_SURROUND = FRONT_LEFT | FRONT_RIGHT | FRONT_CENTER | LOW_FREQUENCY | BACK_LEFT | BACK_RIGHT | SIDE_LEFT | SIDE_RIGHT
    }
}
