name: Publish to nuget
on:
  push:
    branches:
      - dev/publish # Default release branch

env:
  VERSION: '0.0.${{github.run_number}}-alpha'

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        
      - name: Build solution and generate NtFreX.Audio NuGet package
        run: |  
          cd src/NtFreX.Audio
          dotnet pack -c Release -o out --version-suffix ${{env.VERSION}}
      
      - name: Build solution and generate NtFreX.Audio.Wasapi NuGet package
        run: |  
          cd src/adapters/NtFreX.Audio.Wasapi
          dotnet pack -c Release -o out --version-suffix ${{env.VERSION}}
          
      - name: Push generated package to GitHub registry
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/NtFreX/index.json --name "Github" --username "NtFreX" --password ${{secrets.GITHUB_TOKEN}}
          dotnet nuget push ./src/NtFreX.Audio/out/NtFreX.Audio.0.0.1-alpha.nupkg --skip-duplicate --no-symbols true --source "Github"
    
      - name: Push generated package to GitHub registry
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/NtFreX/index.json --name "Github" --username "NtFreX" --password ${{secrets.GITHUB_TOKEN}}
          dotnet nuget push ./src/adapters/NtFreX.Audio.Wasapi/out/NtFreX.Audio.Wasapi.0.0.1-alpha.nupkg --skip-duplicate --no-symbols true --source "Github"
